# Generated by Django 5.2.1 on 2025-06-04 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0002_usuario_produto_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
    ]
