# Generated by Django 5.2.1 on 2025-06-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0004_perfil_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='perfil',
            name='is_vendedor',
            field=models.BooleanField(default=False),
        ),
    ]
